### ISSUE TITLE
Design 2.0

### ISSUE THREAD

**Issue by ulgens** [pyistanbul/website#123]
Recovered/converted version of https://github.com/pyistanbul/website/pull/76

# Pyistanbul Website 2.0

Yeni [pyistanbul.org](http://pyistanbul.org/) tasarımı için temel branch. Aşağıya ilgili sayfalar ve eksik işler için issue bağlantılarını ekledim.

### Anasayfa

- [x] Etkinlik yok
- [ ] Etkinlik yaklaşıyor
  - [ ] Tasarım [issue](https://github.com/pyistanbul/website/issues/77)
- [ ] Etkinlik zamanı
  - [ ] Tasarım [issue](https://github.com/pyistanbul/website/issues/78)
  - [ ] Etkinlik anındaki twitter hashtag akışı [issue](https://github.com/pyistanbul/website/issues/79)
- [ ] Geçmiş etkinlik alanı
  - [x] Tasarım
  - [ ] Bağlantı ekleme [issue](https://github.com/pyistanbul/website/issues/80)
- [ ] Email listesi [issue](https://github.com/pyistanbul/website/issues/81)

Etkinlik yaklaşıyor şablonu
<img width="358" alt="screen shot 2019-01-07 at 02 50 38" src="https://user-images.githubusercontent.com/4904494/50743299-17925000-1227-11e9-8840-30fac697af42.png">

Etkinlik zamanı şablonu
<img width="355" alt="screen shot 2019-01-07 at 02 51 33" src="https://user-images.githubusercontent.com/4904494/50743318-47d9ee80-1227-11e9-9d2d-68205dba8cbf.png">

Etkinlik yok şablonu
<img width="358" alt="screen shot 2019-01-07 at 02 51 43" src="https://user-images.githubusercontent.com/4904494/50743319-47d9ee80-1227-11e9-9907-ec2041190705.png">

### Sunumlar

<img width="359" alt="screen shot 2019-01-07 at 02 49 23" src="https://user-images.githubusercontent.com/4904494/50743284-e31e9400-1226-11e9-8fec-f79519f43e59.png">

- [x] Tasarım
- [ ] İnsanlar bağlantısı [issue](https://github.com/pyistanbul/website/issues/83)

### İnsanlar

<img width="356" alt="screen shot 2019-01-07 at 02 54 25" src="https://user-images.githubusercontent.com/4904494/50743342-95565b80-1227-11e9-8a28-9ebd7d032229.png">

- [x] Tasarım
- [ ] Github login ile profil bağlantısı ekleyebilme [issue](https://github.com/pyistanbul/website/issues/82)

### Blog

- [ ] Sayfa, tasarım [issue](https://github.com/pyistanbul/website/issues/84)
